name: BetterDeathScreen
main: me.tedesk.BetterDeathScreen
description: Plugin that offers a wide variety of options to customize the death screen of Minecraft.
version: ${project.version}
author: Tedesk
depend: [ ProtocolLib ]
api-version: 1.13

commands:
  bds:
    description: Main command of the plugin.
    usage: /<command>