name: BetterDeathScreen
main: me.tedesk.plugin.BetterDeathScreen
version: ${project.version}
author: Tedesk
depend: [ ProtocolLib ]
api-version: 1.13

commands:
  bds:
    description: Main command of the plugin.
    usage: /<command>